name: credit_score
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  bloc: ^8.1.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  envied: ^0.3.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  http: ^0.13.5
  json_annotation: ^4.8.0
  pretty_string: ^1.0.1

dev_dependencies:
  bloc_test: ^9.1.1
  build_runner: ^2.3.3
  envied_generator: ^0.3.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
